<?php
/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on https://tailwindcomponents.com/component/nestable-dropdown-menu
 *
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<div x-ref="nav-mobile" data-navtype="nav-mobile"
     @load.window="menu.setActiveMenu($refs['nav-mobile'])"
     class="bg-primary lg:hidden"
     :class="{'min-h-screen fixed top-0 left-0 w-full' : menu.open}"
     @toggle-mobile-menu.window="menu.open = !menu.open;"
     @keydown.window.escape="menu.open=false"
>
    <div class="flex items-baseline justify-between menu-icon bg-transparent">
        <div class="flex justify-start w-full">
            <a @click="$dispatch('toggle-mobile-menu');"
               class="flex items-center justify-center cursor-pointer"
               :class="{ 'ml-auto': menu.open }">
                <svg class="hidden w-16 h-16 p-4 fill-current"
                     :class="{ 'hidden' : !menu.open, 'block': menu.open }"
                     xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                     viewBox="0 0 20 20">
                    <path
                        fill-rule="evenodd" clip-rule="evenodd"
                        d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0
                          1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828
                          4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z">
                    </path>
                </svg>
                <svg class="block w-12 h-12 p-3 fill-current"
                     :class="{ 'hidden' : menu.open, 'block': !menu.open }"
                     xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                     viewBox="0 0 20 20">
                    <path
                        d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                    </path>
                </svg>
            </a>
        </div>
    </div>

    <nav id="nav-mobile-container"
        class="nav-mobile hidden w-full duration-150 ease-in-out transform border-t transition-display
        border-container bg-secondary h-screen overflow-y-auto pb-20"
        :class="{ 'hidden' : !menu.open }">
        <?= $block->getLayout()->getBlock('topmenu_multimenu_desktop')
            ->setData('menu_items', $block->getMenuItems())
            ->setData('show_icons', $block->getShowIcons())
            ->toHtml(); ?>

    </nav>
</div>

