<?php

/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on https://tailwindcomponents.com/component/nestable-dropdown-menu
 *
 */

use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$parentData = $block->getParentData();

?>
<ul id="parent-<?= $escaper->escapeHtmlAttr($parentData['id']); ?>"
    class="level-<?= $escaper->escapeHtmlAttr($block->getChildLevel()); ?>
    bg-secondary border rounded-sm absolute transition duration-150 ease-in-out
min-w-32 mt-0 mr-0 <?= $block->getChildCss(); ?> <?= $escaper->escapeHtmlAttr($parentData['id']); ?>"
    style="z-index:0"
>
    <?php foreach ($parentData['childData'] as $subMenuIndex => $subMenuItem): ?>
        <?php if (!empty($subMenuItem['childData'])): ?>
            <!-- This is the container for x-data -->
            <li class="rounded-sm relative px-3 py-1 hover:bg-secondary-darker <?= $escaper->escapeHtml($subMenuItem['menu_css_class']) ?>">
                <button @mouseenter.debounce="{ menu.checkSlideDirection($event) }" id="hover-<?= $escaper->escapeHtmlAttr($subMenuIndex) ?>"
                        class="w-full text-left flex items-center outline-none focus:outline-none <?= $escaper->escapeHtmlAttr($subMenuIndex) ?>">
                                            <span
                                                class="pr-1 flex-1">
                                                    <a href="<?= $escaper->escapeHtmlAttr($subMenuItem['url']) ?>"
                                                       title="Click to view all <?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                                       class="block w-full whitespace-nowrap first:mt-0 hover:underline">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                                    </a>
                                            </span>
                    <?php if (!empty($subMenuItem['childData'])): ?>
                        <span @click="menu.handleMobileOpenMenu($event)" class="mr-auto">
                                      <svg class="fill-current h-4 w-4 transition duration-150 ease-in-out"
                                           xmlns="http://www.w3.org/2000/svg"
                                           viewBox="0 0 20 20">
                                        <path
                                            d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                                      </svg>

                                    </span>
                    <?php endif; ?>
                </button>
                <?php if (!empty($subMenuItem['childData'])): ?>
                    <?= $block->getLayout()->getBlock('topmenu_multimenu_childitems')
                        ->setData('parent_data', $subMenuItem)
                        ->setData('child_css', 'top-0 right-0 origin-top-left')
                        ->setData('child_level', $block->getChildLevel() + 1)
                        ->toHtml(); ?>
                <?php endif; ?>
            </li>
        <?php else: ?>
            <li class="rounded-sm px-0 py-1 px-3 hover:bg-secondary-darker <?= $escaper->escapeHtmlAttr($subMenuIndex) ?>">
                <a href="<?= $escaper->escapeHtmlAttr($subMenuItem['url']) ?>"
                   title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                   class="block w-full whitespace-nowrap first:mt-0 hover:underline">
                    <?= $escaper->escapeHtml(substr($subMenuItem['name'], 0, 30)) ?>
                    <?php if (strlen($subMenuItem['name']) > 30): ?>
                        ...
                    <?php endif; ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>

