<?php
/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on https://tailwindcomponents.com/component/nestable-dropdown-menu
 *
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$menuItems = $block->getMenuItems();

?>
<?php foreach ($menuItems as $index => $menuItem): ?>
    <div class="group group-<?= /* @noEscape */
    (string)$index ?> <?= $escaper->escapeHtml($menuItem['menu_css_class']) ?>">
        <button
            @click="menu.hoverPanelActiveId = '<?= /* @noEscape */
            (string)$index ?>'"
            class="uppercase border-none bg-transparent outline-none focus:outline-none border px-3 py-1 h-10 rounded-sm flex items-center min-w-32 hover:bg-secondary-darker"
            :class="{ 'bg-secondary-darker' : '<?= $menuItem['has_active'] ?>' }">
                        <span class="pr-1 font-normal flex-1">
                                <a href="<?= $escaper->escapeHtmlAttr($menuItem['url']) ?>"
                                   title="Click to view all <?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                   class="block w-full whitespace-nowrap first:mt-0">
                            <?= $escaper->escapeHtmlAttr($menuItem['name']) ?>
                                </a>
                        </span>
            <?php if (!empty($menuItem['childData'])): ?>
                <span @click.prevent="menu.handleMobileOpenMenu($event)">
                      <svg
                          class="fill-current h-4 w-4 transform group-hover:-rotate-180 transition duration-150 ease-in-out control"
                          xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                      </svg>
                    </span>
            <?php endif; ?>
        </button>
        <?php if (!empty($menuItem['childData'])): ?>
            <?= $block->getLayout()->getBlock('topmenu_multimenu_childitems')
                ->setData('parent_data', $menuItem)
                ->setData('child_css', 'border-t-0 transform scale-0 group-hover:scale-100 origin-top')
                ->setData('child_level', 1)
                ->toHtml(); ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
<?php echo $block->getChildHtml('topmenu.additional'); ?>

