<?php

/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on default hyva mobile menu
 *
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use ProxiBlue\MultiMenu\ViewModel\Image;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Image $image */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$image = $viewModels->require(Image::class);
$menuItem = $block->getMenuItem();
$index = $block->getMenuIndex();
$parentIndex = $block->getParentIndex();
$menuLevel = $block->getMenuLevel();

?>
<div
    data-menu-id="<?= $escaper->escapeHtmLAttr($index) ?>"
    data-parent-id="<?= $escaper->escapeHtmLAttr($parentIndex) ?>"
    class="child-menu-container absolute top-0 right-0 z-10 flex flex-col w-full h-full bg-container-lighter
    <?php if($menuLevel == 1):?> pl-1 pr-1 pt-[1.2px] <?php endif; ?>"
    :class="{ 'hidden': getMobilePanelShow('<?= /* @noEscape */(string) $parentIndex ?>', '<?= /* @noEscape */(string) $index ?>') === false }"
>
    <ul
        class="child-menu-container-ul transition-transform duration-200 ease-in-out translate-x-full transform "
        :class="{ 'translate-x-full' : getMobilePanelShow('<?= /* @noEscape */
        (string) $parentIndex ?>', '<?= /* @noEscape */
        (string) $index ?>') === false }"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
    >
        <li class="mobile-action-container grid gap-0 grid-cols-2 grid-rows-1 min-h-[74px]">
            <div class="back-container">
                <?php if ($parentIndex == 'top-level'): ?>
                    <button
                        type="button"
                        class="px-8 py-6 cursor-pointer z-1"
                        @click="backToParent('top-level')"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main menu')) ?>"
                    >
                        <?= $heroicons->chevronLeftHtml('inline', 24, 24,
                            ["aria-hidden" => "true"]); ?>
                        <span class="ml-4 inline">
                    <?= $escaper->escapeHtmlAttr(__('Back to main menu')) ?>
                </span>
                    </button>
                <?php else:
                    $baseMenuItems = $block->getParentBlock()
                        ->getParentBlock()
                        ->getMenuItems();
                    ?>
                    <button
                        type="button"
                        class="px-8 py-6 cursor-pointer z-1"
                        @click="backToParent('<?= /* @noEscape */
                        $parentIndex ?>')"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to parent top level') . $menuItem['name']) ?>"
                    >
                        <?= $heroicons->chevronLeftHtml('inline', 24, 24,
                            ["aria-hidden" => "true"]); ?>
                        <span class="ml-4 inline">
                    <?= $escaper->escapeHtmlAttr(__('Back to ')) ?> <?= $escaper->escapeHtml($baseMenuItems[$parentIndex]['name']) ?>
                </span>
                    </button>
                <?php endif; ?>
            </div>
            <div class="action-container text-right">
                <?php if ($parentIndex != 'top-level'): ?>
                    <button
                        @click="backToTopMenu()"
                        class="inline z-1"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to top menu')) ?>"
                        :class="{ 'hidden': getCloseMenuShow('<?= /* @noEscape */
                        (string) $index ?>') === false }"
                    >
                        <?= $heroicons->chevronDoubleLeftHtml
                        ('inline mt-1', 24, 24,
                            [
                                "aria-hidden" => "true",
                            ]
                        );
                        ?>
                    </button>
                <?php endif; ?>
                <button
                    @click="closeMenu()"
                    class="inline z-1"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                    :class="{ 'hidden': getCloseMenuShow('<?= /* @noEscape */
                    (string) $index ?>') === false }"
                >
                    <?= $heroicons->xHtml('hidden p-4 inline mt-1', 64, 64, [
                        ":class" => "{ 'hidden' : !open, 'block': open }",
                        "aria-hidden" => "true",
                    ]) ?>
                </button>
            </div>
        </li>
        <li class="menu-header border-b text-center pt-4 pb-4">
            <span
                class="menu-header-text font-bold"><?= $escaper->escapeHtml($menuItem['name']) ?></span>
        </li>
        <?php foreach ($menuItem['childData'] as $subMenuIndex => $subMenuItem): ?>
            <li data-child-id="<?= $escaper->escapeHtmLAttr($subMenuIndex) ?>-main"
                data-parent-id="<?= $escaper->escapeHtmLAttr($parentIndex) ?>"
                class="level-<?= $menuLevel ?>"
            >
                <div
                    class="flex items-center transition-transform duration-0 ease-in-out transform"
                >
                    <a
                        href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                bg-container-lighter border-container
                                            "
                    >
                                            <span
                                                class="ml-10 text-base text-gray-700">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                    </a>
                    <?php if (!empty($subMenuItem['childData'])): ?>
                        <button
                            @click="openSubcategory('<?= /* @noEscape */
                            $index ?>','<?= /* @noEscape */
                            $subMenuIndex ?>')"
                            class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                bg-container-lighter border-container"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories',
                                $subMenuItem['name'])) ?>"
                            aria-haspopup="true"
                        >
                            <div class="w-8 h-8 border rounded">
                                <?= $heroicons->chevronRightHtml('w-full h-full p-1',
                                    24, 24, ["aria-hidden" => "true"]) ?>
                            </div>
                        </button>
                    <?php endif; ?>
                </div>
                <?php if (!empty($subMenuItem['childData'])): ?>
                    <?= $block->getLayout()
                        ->getBlock('topmenu_multimenu_mobile_childitems')
                        ->setData('parent_index', $index)
                        ->setData('menu_index', $subMenuIndex)
                        ->setData('menu_item', $subMenuItem)
                        ->setData('menu_level', $menuLevel + 1)
                        ->toHtml(); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

