<?php

/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on https://tailwindcomponents.com/component/nestable-dropdown-menu
 *
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use ProxiBlue\MultiMenu\ViewModel\Image;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Image $image */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$image = $viewModels->require(Image::class);
$menuItem = $block->getMenuItem();
$index = $block->getMenuIndex();
$parentIndex = $block->getParentIndex();
$menuLevel = $block->getMenuLevel();

?>

<div
    data-menu-id="<?= $escaper->escapeHtmLAttr($index) ?>" data-parent-id="<?= $escaper->escapeHtmLAttr($parentIndex) ?>"
    class="child-menu-container absolute top-0 right-0 z-10 flex flex-col gap-1 w-full h-full p-1 bg-container-lighter"
    :class="{ 'hidden': getMobilePanelShow('<?= /* @noEscape */(string) $parentIndex ?>', '<?= /* @noEscape */(string) $index ?>') === false }"
>
    <ul
        class="child-menu-container-ul mt-16 transition-transform duration-200 ease-in-out translate-x-full transform "
        :class="{ 'translate-x-full' : getMobilePanelShowUl('<?= /* @noEscape */(string) $parentIndex ?>', '<?= /* @noEscape */(string) $index ?>') === false }"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
    >
        <li>
            <button
                type="button"
                class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container w-full border-t"
                @click="backToParent('<?= /* @noEscape */$index ?>-main')"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Back to parent %s',
                    $menuItem['name'])) ?>"
            >
                <?= $heroicons->chevronLeftHtml('', 24, 24,
                    ["aria-hidden" => "true"]); ?>
                <span class="ml-4">
                                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                                        </span>
            </button>
        </li>
        <?php foreach ($menuItem['childData'] as $subMenuIndex => $subMenuItem): ?>
            <li data-child-id="<?= $escaper->escapeHtmLAttr($subMenuIndex) ?>-main"
                class="level-<?= $menuLevel ?>"
            >
                <div
                    class="flex items-center transition-transform duration-150 ease-in-out transform"
                >
                    <a
                        href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                bg-container-lighter border-container
                                            "
                    >
                                            <span
                                                class="ml-10 text-base text-gray-700">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                    </a>
                    <?php if (!empty($subMenuItem['childData'])): ?>
                        <button
                            @click="openSubcategory('<?= /* @noEscape */$index ?>','<?= /* @noEscape */$subMenuIndex ?>')"
                            class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                bg-container-lighter border-container"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories',
                                $subMenuItem['name'])) ?>"
                            aria-haspopup="true"
                        >
                            <div class="w-8 h-8 border rounded">
                                <?= $heroicons->chevronRightHtml('w-full h-full p-1',
                                    24, 24, ["aria-hidden" => "true"]) ?>
                            </div>
                        </button>
                    <?php endif; ?>
                </div>
                <?php if (!empty($subMenuItem['childData'])): ?>
                    <?= $block->getLayout()->getBlock('topmenu_multimenu_mobile_childitems')
                        ->setData('parent_index', $index)
                        ->setData('menu_index', $subMenuIndex)
                        ->setData('menu_item', $subMenuItem)
                        ->setData('menu_level', $menuLevel + 1)
                        ->toHtml(); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

