<?php
/*
 * (c) Lucas van Staden <sales@proxiblue.com.au>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * The base menu dropdown was based on https://tailwindcomponents.com/component/nestable-dropdown-menu
 *
 */


use Hyva\Theme\Model\ViewModelRegistry;
use ProxiBlue\MultiMenu\ViewModel\Navigation;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);
$menuItems = $viewModelNavigation->getNavigation($viewModelNavigation->getCategoryDepth());

?>
<div class="z-40 order-2 sm:order-1 lg:order-2 navigation">
    <!-- mobile -->
    <div x-ref="nav-mobile" data-navtype="nav-mobile"
         @load.window="menu.setActiveMenu($refs['nav-mobile'])"
         class="bg-secondary lg:hidden w-12"
         :class="{'min-h-screen fixed top-0 left-0 w-full' : menu.open}"
         @toggle-mobile-menu.window="menu.open = !menu.open"
         @keydown.window.escape="menu.open=false"
    >
        <div class="bg-primary flex items-baseline justify-between menu-icon">
            <div class="flex justify-end w-full">
                <a @click="$dispatch('toggle-mobile-menu')"
                   class="flex items-center justify-center cursor-pointer"
                   :class="{ 'ml-auto': menu.open }">
                    <svg class="hidden w-16 h-16 p-4 fill-current"
                         :class="{ 'hidden' : !menu.open, 'block': menu.open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                            fill-rule="evenodd" clip-rule="evenodd"
                            d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0
                          1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828
                          4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z">
                        </path>
                    </svg>
                    <svg class="block w-12 h-12 p-3 fill-current"
                         :class="{ 'hidden' : menu.open, 'block': !menu.open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                            d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                        </path>
                    </svg>
                </a>
            </div>
        </div>

        <nav
            class="z-40 hidden w-full duration-150 ease-in-out transform border-t transition-display border-container"
            :class="{ 'hidden' : !menu.open }"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <div class="level-0 ">
                <span id="menu_item_<?= $index ?>_container"
                      class="flex items-center transition-transform duration-150 ease-in-out transform">
                    <a class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                        bg-secondary border-container hover:bg-container-darker hover:underline level-0"
                       href="<?= $escaper->escapeHtmlAttr($menuItem['url']) ?>"
                       title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>">
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <a class="absolute right-0 flex w-8 h-8 mr-8 border rounded cursor-pointer
                        bg-secondary border-container hover:bg-container hover:border-container"
                           @click="menu.mobilePanelActiveId =
                          menu.mobilePanelActiveId === '<?= /* @noEscape */
                           (string)$index ?>' ?
                           0 : '<?= /* @noEscape */
                           (string)$index ?>'; swapCssClass('<?= /* @noEscape */
                           (string)$index ?>');
                            document.getElementById('menu_item_<?= $index ?>_children').classList.remove('overflow-y-scroll');"

                        >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24" width="24"
                             stroke="currentColor"
                             class="w-full h-full p-1"
                        >
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                        </svg>
                    </a>
                    <?php endif; ?>
                </span>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div id="menu_item_<?= $index ?>_children"
                             class="overflow-y-scroll absolute top-0 right-0 z-40 w-full h-full transition-transform duration-200 ease-in-out h-screen
                            translate-x-full transform bg-secondary pb-32">
                            <a class="flex items-center px-8 py-4 border-b cursor-pointer bg-primary-lighter border-container"
                               @click="menu.mobilePanelActiveId = 0; swapCssClassBack('<?= /* @noEscape */
                               (string)$index ?>');"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24"
                                     width="24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M15 19l-7-7 7-7"/>
                                </svg>
                                <span class="ml-4 color-primary">
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </span>
                            </a>
                            <a href="<?= $escaper->escapeHtmlAttr($menuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                               class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                            bg-secondary border-container hover:bg-container-darker hover:underline"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24" height="24"
                                     width="24"></svg>
                                <span class="ml-4"><?= $escaper->escapeHtml(__('View All')) ?></span></a>
                            <?php foreach ($menuItem['childData'] as $submenuItemIndex => $subMenuItem): ?>
                                <div class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-secondary border-container hover:bg-container-darker hover:underline">
                                    <a href="<?= $escaper->escapeHtmlAttr($subMenuItem['url']) ?>"
                                       title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                         viewBox="0 0 24 24" height="24"
                                         width="24"></svg>
                                    <span class="ml-4 text-base text-white lg:ml-0">
                                            <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                        </span>
                                    </a>
                                    <?php /* SUB SUB MENU OPEN ICON */ ?>
                                    <?php if (!empty($subMenuItem['childData'])): ?>
                                        <a class="absolute right-0 flex w-8 h-8 mr-8 border rounded cursor-pointer bg-secondary border-container hover:bg-container hover:border-container"
                                           @click="menu.mobilePanelActiveId = '<?= /* @noEscape */
                                           (string)$submenuItemIndex ?>';
                                           swapCssClassIn('<?= $submenuItemIndex ?>_container');
                                           swapCssClassOut('<?= $index ?>_container');
                                           document.getElementById('menu_item_<?= $index ?>_children').classList.remove('overflow-y-scroll');
                                            ">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                 height="24" width="24"
                                                 stroke="green"
                                                 class="w-full h-full p-1"
                                            >
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                      d="M9 5l7 7-7 7"/>
                                            </svg>
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <?php /* SUB SUB MENU TITLE / BACK / VIEW ALL */ ?>
                                <?php if (!empty($subMenuItem['childData'])): ?>
                                    <div id="menu_item_<?= $submenuItemIndex ?>_container"
                                         class="subsubmenu-start overflow-y-scroll absolute top-0 right-0 z-40 w-full h-full transition-transform duration-200 ease-in-out h-screen
                            translate-x-full transform bg-secondary pb-32">
                                        <a class="flex items-center px-8 py-4 border-b cursor-pointer bg-primary-lighter border-container"
                                           @click="menu.mobilePanelActiveId = '<?= /* @noEscape */
                                           (string)$submenuItemIndex ?>';
                                           swapCssClassOut('<?= $submenuItemIndex ?>_container');
                                           swapCssClassIn('<?= $index ?>_container');
                                           document.getElementById('menu_item_<?= $index ?>_children').classList.add('overflow-y-scroll');">

                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                 height="24"
                                                 width="24"
                                                 stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                      d="M15 19l-7-7 7-7"/>
                                            </svg>
                                            <span
                                                class="ml-4 color-primary"><?= $escaper->escapeHtml($subMenuItem['name']) ?></span>
                                        </a>
                                        <a href="<?= $escaper->escapeHtmlAttr($subMenuItem['url']) ?>"
                                           title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                           class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                            bg-secondary border-container hover:bg-container-darker hover:underline"
                                        >
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                 viewBox="0 0 24 24" height="24"
                                                 width="24"></svg>
                                            <span
                                                class="ml-4"><?= $escaper->escapeHtml(__('View All')) ?></span></a>
                                        <?php foreach ($subMenuItem['childData'] as $subSubmenuItemIndex => $subSubMenuItem): ?>
                                            <div class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-secondary border-container hover:bg-container-darker hover:underline">
                                                <a href="<?= $escaper->escapeHtmlAttr($subSubMenuItem['url']) ?>"
                                                   title="<?= $escaper->escapeHtmlAttr($subSubMenuItem['name']) ?>"
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                     viewBox="0 0 24 24" height="24"
                                                     width="24"></svg>
                                                <span class="ml-4 text-base text-white lg:ml-0">
                                            <?= $escaper->escapeHtml($subSubMenuItem['name']) ?>
                                        </span>
                                                </a>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>

                                <?php endif; /* END SUB SUB MENU ITEMS */ ?>

                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </nav>
    </div>

    <!-- desktop -->
    <div x-ref="nav-desktop" data-navtype="nav-desktop"
         @load.window="menu.setActiveMenu($refs['nav-desktop']);"
         class=" lg:pl-0 lg:pr-0 hidden lg:block lg:relative lg:min-h-0 lg:px-8 lg:w-auto lg:pt-0">
        <nav class="nav-desktop flex">
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <div class="group group-<?= /* @noEscape */
                (string)$index ?> <?= $escaper->escapeHtml($menuItem['menu_css_class']) ?>">
                    <button
                        @click="menu.hoverPanelActiveId = '<?= /* @noEscape */
                        (string)$index ?>'"
                        class="uppercase border-none bg-transparent outline-none focus:outline-none border px-3 py-1 h-10 rounded-sm flex items-center min-w-32 hover:bg-secondary-darker"
                        :class="{ 'bg-secondary-darker' : '<?= $menuItem['has_active'] ?>' }">
                        <span class="pr-1 font-normal flex-1">
                                <a href="<?= $escaper->escapeHtmlAttr($menuItem['url']) ?>"
                                   title="Click to view all <?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                   class="block w-full whitespace-nowrap first:mt-0">
                            <?= $escaper->escapeHtmlAttr($menuItem['name']) ?>
                                </a>
                        </span>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <span>
                      <svg
                          class="fill-current h-4 w-4 transform group-hover:-rotate-180 transition duration-150 ease-in-out"
                          xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                      </svg>
                    </span>
                        <?php endif; ?>
                    </button>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <?= $block->getLayout()->getBlock('topmenu_multimenu_chidlitems')
                            ->setData('parent_data', $menuItem)
                            ->setData('child_css', 'border-t-0 transform scale-0 group-hover:scale-100 origin-top')
                            ->setData('child_level', 1)
                            ->toHtml(); ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
            <?php echo $block->getChildHtml('topmenu.additional'); ?>
        </nav>
    </div>

</div>
<script>
    'use strict';

    const initHeaderNavigation = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            slideToLeft: false,
            activeMenu: 'nav-desktop',
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0').classList.add('underline');
                });
                this.activeMenu = menuNode.dataset.navtype;
            },
            checkSlideDirection(event) {
                if (this.activeMenu == 'nav-desktop') {
                    let domElm = event.target
                    if (domElm.nextElementSibling) {
                        let UlElm = domElm.nextElementSibling;
                        return new Promise((resolve, reject) => {
                            UlElm.classList.remove('slide-to-left');
                            UlElm.classList.remove('slide-to-right')
                            return resolve();
                        })
                            .then(() => {
                                if ((domElm.getBoundingClientRect().right + UlElm.offsetWidth) > window.innerWidth) {
                                    UlElm.style.zIndex = -1;
                                    UlElm.classList.add('slide-to-left')
                                    this.slideToLeft = true;
                                } else {
                                    UlElm.classList.add('slide-to-right');
                                    this.slideToLeft = false;
                                }
                            });

                    }
                }
            }
        }
    }

    function swapCssClass(elm) {
        let domElm = document.getElementById('menu_item_' + elm + '_container');
        domElm.classList.remove('translate-x-0');
        domElm.classList.add('translate-x-full');
        domElm = document.getElementById('menu_item_' + elm + '_children');
        domElm.classList.add('translate-x-0');
        domElm.classList.remove('translate-x-full');
    }

    function swapCssClassBack(elm) {
        let domElm = document.getElementById('menu_item_' + elm + '_container');
        domElm.classList.add('translate-x-0');
        domElm.classList.remove('translate-x-full');
        domElm = document.getElementById('menu_item_' + elm + '_children');
        domElm.classList.remove('translate-x-0');
        domElm.classList.add('translate-x-full');
    }

    function swapCssClassIn(elm) {
        let domElm = document.getElementById('menu_item_' + elm);
        domElm.classList.add('translate-x-0');
        domElm.classList.remove('translate-x-full');
    }

    function swapCssClassOut(elm) {
        let domElm = document.getElementById('menu_item_' + elm);
        domElm.classList.remove('translate-x-0');
        domElm.classList.add('translate-x-full');
    }
</script>
